parameters:
  bin-dir: ./vendor/bin
  git-dir: .
  hooks-dir: ~
  hooks-preset: local
  process-timeout: 60
  process-async-wait: 1000
  process-async-limit: 10
  stop-on-failure: false
  ignore-unstaged-changes: false
  skip-success-output: false
  message:
    successfully: successfully.txt
    failed: failed.txt
  extensions: []
  tasks: ~
  git-hooks:
    commit-msg: ~
    pre-commit: ~
    pre-push: ~
  commands: ~
