services:
  task.ant:
      class: ClickNow\Checker\Task\Ant
      arguments:
        - '@process.process-builder'
        - '@formatter.raw-process'
      tags:
        - { name: checker.task, config: ant }

  task.gherkin:
    class: ClickNow\Checker\Task\Gherkin
    arguments:
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: gherkin }

  task.grunt:
    class: ClickNow\Checker\Task\Grunt
    arguments:
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: grunt }

  task.gulp:
    class: ClickNow\Checker\Task\Gulp
    arguments:
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: gulp }

  task.make:
    class: ClickNow\Checker\Task\Make
    arguments:
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: make }

  task.robo:
    class: ClickNow\Checker\Task\Robo
    arguments:
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: robo }
