services:
  task.ant:
    class: ClickNow\Checker\Task\Ant
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: ant }

  task.atoum:
    class: ClickNow\Checker\Task\Atoum
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: atoum }

  task.behat:
    class: ClickNow\Checker\Task\Behat
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: behat }

  task.brunch:
    class: ClickNow\Checker\Task\Brunch
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: brunch }

  task.codeception:
    class: ClickNow\Checker\Task\Codeception
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: codeception }

  task.doctrine-orm:
    class: ClickNow\Checker\Task\DoctrineOrm
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: doctrine-orm }

  task.gherkin:
    class: ClickNow\Checker\Task\Gherkin
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: gherkin }

  task.grunt:
    class: ClickNow\Checker\Task\Grunt
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: grunt }

  task.gulp:
    class: ClickNow\Checker\Task\Gulp
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: gulp }

  task.make:
    class: ClickNow\Checker\Task\Make
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: make }

  task.npm-script:
    class: ClickNow\Checker\Task\NpmScript
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: npm-script }

  task.php7cc:
    class: ClickNow\Checker\Task\Php7cc
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: php7cc }

  task.phpcpd:
    class: ClickNow\Checker\Task\PhpCpd
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: phpcpd }

  task.phplint:
    class: ClickNow\Checker\Task\PhpLint
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: phplint }

  task.phpmd:
    class: ClickNow\Checker\Task\PhpMd
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: phpmd }

  task.phpunit:
    class: ClickNow\Checker\Task\PhpUnit
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: phpunit }

  task.robo:
    class: ClickNow\Checker\Task\Robo
    arguments:
      - '@io'
      - '@repository.filesystem'
      - '@process.process-builder'
      - '@formatter.raw-process'
    tags:
      - { name: checker.task, config: robo }
