services:
  process.arguments_collection:
    class: ClickNow\Checker\Process\ArgumentsCollection

  process.executable_finder:
    class: ClickNow\Checker\Process\ExecutableFinder
    arguments:
      - '%bin_dir%'
      - '@executable_finder'

  process.process_builder:
    class: ClickNow\Checker\Process\ProcessBuilder
    arguments:
      - '@process.executable_finder'
      - '@process_builder'
      - '@io'
      - '@process.platform'

  process.platform:
    class: ClickNow\Checker\Process\Platform
      - '@process_builder'
      - '@io'
