services:
  repository.files_collection:
    class: ClickNow\Checker\Repository\FilesCollection

  repository.git:
    class: ClickNow\Checker\Repository\Git
    arguments:
      - '@git.repository'
      - '@filesystem'
